apiVersion: ENC[AES256_GCM,data:Fjo=,iv:LFV20TmFneaX1tCyiJxzCI7Dlxq4SqBdeEy46YZsXvo=,tag:J4Y/Ree55nvk8xUEjTKYsQ==,type:str]
kind: ENC[AES256_GCM,data:s38zK/IX,iv:qin+DA3wzL40YSwvgxuLnUZAsvAKhxrD/+2dR9rP7us=,tag:MnKKUd6C/Pz4KmBDU+TSZA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:aEwZCG0x+AgjOsU4hQ==,iv:Qt3FQxd4HZay6DAjzZG6XOSDteiWOELMqZAcEK2QfpA=,tag:kHAGSa4neAnQml6dJVuKXQ==,type:str]
    namespace: ENC[AES256_GCM,data:3UyfILpUv2Sgmg==,iv:FeDtlxXki+QUSMxbkHIWVpi2TPi5CEob3z4aeBsp/qc=,tag:Pc/LCsksqjTNepj7z8yHqA==,type:str]
type: ENC[AES256_GCM,data:ueAHbq3M,iv:3Xab7q8HYLQUktv/2XZfkfG49XH8rEO0WTJSSoDzQII=,tag:QzouZdn7ezT+zTLEC9h4/g==,type:str]
stringData:
    #ENC[AES256_GCM,data:KER1CnXi09K+ShBTJ8QK5dCPa6U4YlXfFybQSkL1sN8FxOs3DUvYSSvJUwmRIVTqarakuFB+6cnudpKvyJQl4UBjxA==,iv:65KHyCaMDSwfuABy9xfpiD/xC12r1VYdh/pl4IxXFPY=,tag:h85imxuLggW5/2bPHeyLLQ==,type:comment]
    #ENC[AES256_GCM,data:Xk8vI96HW4pg8fS7S6VosSZrLrdmSu28YPvv+bnoscxmf0JnPdNKmpargFS6vXdC1qtt1vIrAWCH9o/7ia0yV6Gv,iv:7tVmrpabWH0wmf/TLkRtuQDx6WlsbJpnuooEEaKlK1o=,tag:wJDZ276GevwTwKcb96cFdg==,type:comment]
    #ENC[AES256_GCM,data:9HR4VQbf4H6q0mTsKFlfumiNTZk3IY9lIu7R6uvi2Hmcpw63kLsZ4PfX/swP0ZnLtBpulG99wpYvEixcGGJD/MmFz1E=,iv:vuuGKK6XnX92l3hHqTCmXkrj0HvdXinBWxoq7XZc1Q8=,tag:AaX5jAFE70tEmp1M4IISrA==,type:comment]
    #ENC[AES256_GCM,data:o28fiKBC/lLHkJ7tvCo+yWzojF1WdmMQ,iv:aK/PKEwM1HKyr+p5KS4LAOUVBNwC+H6ivb6aEoD+Cpw=,tag:l0zCdDhSd063eH1GVKn57w==,type:comment]
    GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:62TPvENRMJQwe3N9IE9xKMPmqJic9P/s,iv:JCjBD/OuFMDUOK1AfW1Q3Qfld3DgaFVUiFMgUArtmvo=,tag:gNgw/+PywDRoYAaBrw939g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCbE90VVVGUDg5Ukh2MUxz
            UVQwVDVpK2JEUG5TK0VMWS9LVXpyRXhWU1ZRClQxTkJ2aUM1cU1jeVpjLzQ1VXZX
            M1pzL29LakxDLzJaOUkycGRlMUlOYm8KLS0tIEdIaG5GNmx4ekk2ZTdSNWgrTmNQ
            cStSV2VjaW44MkQxSnhJMk5BUnBnbWMKbQwIPtPyvwyLBSwM1iXoqEGeOtL+h5T+
            Lok90C1ltX+yMYqeX8PKaLwnwjnbNpjsbp5bK2Ngn/zZaMUzPmd01A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age182ep8d0hyvnwfj3nhzv64xrdvm4fwpudc0wvvkxncqygzzpxkeks4mldng
    lastmodified: "2026-10-06T19:42:16Z"
    mac: ENC[AES256_GCM,data:xgeIYrna3gS7NgtO/Gu7gjTBt7HoAXGUvYyKuEvKDfmmcxn777bRU7j+B3izWSfTkr3Xx6fpIR4KBwndFkKSZQCZo+u/jqiMD6j/H8k2k6CATpbR2byBwGCbYNHL3lFWacdJDbs8JMGSzl1QKRnNqSkekt+hJCoKb5HPJxBLCt0=,iv:MeNTFoqxTz+iSziiyHr3pLu4Th5muM5LxxA4ixHvm4s=,tag:zfBGjSA+gHD9V6U6ZKdrgQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
