apiVersion: v1
kind: Service
metadata:
  name: palisade-gateway
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "palisade.labels" . | nindent 4 }}
    app.kubernetes.io/name: palisade-gateway
spec:
  selector:
    app.kubernetes.io/name: palisade-gateway
  ports:
    - name: http
      port: {{ .Values.gateway.port }}
      targetPort: http
