apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "palisade.labels" . | nindent 4 }}
    app.kubernetes.io/name: redis
spec:
  selector:
    app.kubernetes.io/name: redis
  ports:
    - name: redis
      port: {{ .Values.redis.port }}
      targetPort: redis
