apiVersion: v1
kind: Service
metadata:
  name: vllm
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "palisade.labels" . | nindent 4 }}
    app.kubernetes.io/name: vllm
spec:
  selector:
    app.kubernetes.io/name: vllm
  ports:
    - name: http
      port: 8000
      targetPort: http
