apiVersion: ENC[AES256_GCM,data:CKM=,iv:zJ7G06I3jCy6ykjaSydqunM2BaVxFP4epp3DzLMhHzo=,tag:o7taoLB8ahvZn+JLXKtRPQ==,type:str]
kind: ENC[AES256_GCM,data:Oxh9LaeB,iv:l2LaHnhbQa6+6OlHhFIRdjTEDHFms7aSfUffTzLxC8w=,tag:QA/iNwrA+mzoaU8U8JyUbw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:5pKG4rDwZG9jZW9Agw9gtwFgCI5N/FQ=,iv:i3pw3fI1qRWTtF+btv1cmv8clw1PlqJPZb42NAHFDv0=,tag:Xi58P48cX87nJWJ+tJ+pqA==,type:str]
    namespace: ENC[AES256_GCM,data:yV+dg3v/KGs=,iv:/+6MDA1YbY+F9D5/Z1iKk2Tzj5lMd7ooAlncoMV56Lw=,tag:8tcC+BFAB5M5fHwx7oCerw==,type:str]
type: ENC[AES256_GCM,data:nlj7Emvu,iv:KFEs2TsKlCJHhQY22CnKQ9W/K/yA8UnWLW3zsj72T3o=,tag:VMi7KDCdwPziX4dxWJprnA==,type:str]
stringData:
    #ENC[AES256_GCM,data:2Ys59FKrwRP398aFhJoW22F3BZEZRFxydS+Uu3r0uMduxulgSJxHWE62t9NEK5B5y/RAHkSqXMJFiP3mvwxwLZMtnQ==,iv:f2HJSM6G675DT9akZ5CQyzKdF1yJkWDH2R+0OJGttUk=,tag:Lm+GH9XnohrtEh+TNhqBfQ==,type:comment]
    #ENC[AES256_GCM,data:j+JZKNoec5GXji00BhJAP7NHpyafSz1iP2rE/At4cbwhWX65cp5vH+9maQwE1BGNdSn/05dFuLv52wXmkTSNVeBFEf7/,iv:6cvUa6kbzGs9JGmGvzHAn8CMovgbK0zxUvN1ADZj6AI=,tag:OYcm/GwpDFTiNAqDd4XHpA==,type:comment]
    #ENC[AES256_GCM,data:uic42zzrmQAJMmrvQqaB+iRvrJ2vucoDfx0ztckC2IF2EE4CT8m9sW9vS/PEz67ULE2GuI4Cs2lTiaBj2A5rqlZWunh1,iv:fy2jwrTCDO/a4076dJYVPlhOo4yqQps/+0dvJ3N6nU8=,tag:BmN3SWyEwu4hd/7IozLnqw==,type:comment]
    #ENC[AES256_GCM,data:ySs9Z3nWz2/4+tkFGg==,iv:UWp4FFf5bUS0XlOycegBuEFmIakeWFBHF1QTd2D+thk=,tag:tQ9GrUoJL/UF+kM4laJdZA==,type:comment]
    API_KEY_HASHES: ENC[AES256_GCM,data:0ny0Y2Sxcsss0OwB34yP+ECZMqiAzXMKFJc9C84fxDl4X3Ymh+r/BRHp9Ou0VGjkf/fC/SPCq+10Rvj8UMgaHjkqSwhJ+FFn51E2u0ycyGS9Pce0Y4t6oS7/AuylUSvN3ubJf9kWSfLKtKRmmXTiAMmonTJPeqxEKYvvhvRKU0qL,iv:Megj8pZmflHRyC3Z9gDuV70DIqCzkEGpC2gngSQWW5E=,tag:Xct1T1adWJ4/PPTRstQMmQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Z1J0QkhuekJCQUxGajQw
            Rk9nT09YbWsrWWNrQ2ZBQ24yc1B4bmxIU0JZCis2SnEyM0Z1d2FyVUVocDRreVhU
            ZUlSeFhvZ0FjUThZZFdGVXpLbUhwdjAKLS0tIENJalBTNFdRUmJ2THdGVDIxNU84
            aU9rWlZEZjE5OStlNHJaS2g2bkgvcjgKfAzlWA86I2Rj3K/8JD8TwO8XbWFPbbjR
            OFjBD9HThHBT89Xm7ExDsk6XJ4bv7rQOjAZG4mX6sNwOx/YNkEhepQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age182ep8d0hyvnwfj3nhzv64xrdvm4fwpudc0wvvkxncqygzzpxkeks4mldng
    lastmodified: "2026-10-01T10:06:32Z"
    mac: ENC[AES256_GCM,data:XyVTYyr0Y2fuFZaCkWzeR9Dy4n117QessuLuzQHFaM42av8ncylJ1TCq7QDMzdhvA6ud3AW0GNfjjMITLX3oLpS5v5yjdDuvlL4vbLXgW6A2HwtsuXWBY/eml/zgc7m7HtvyIGcNS2wfM600lTzRFZOJN3lk3T7lPWCfcXnYxSQ=,iv:iNKVZ3V+tRnMZluhWmkvgGVrQ2e163LWNF1rcrdJQUo=,tag:WlN27z9VyHiWkOvOh5il7A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
