apiVersion: ENC[AES256_GCM,data:GAg=,iv:a3AQT1gE5j4zMfnB5qkHZ1vt/yb3ElTIPkI46yij8Lo=,tag:zJxjSUEoRR0Hl48SOqfHqA==,type:str]
kind: ENC[AES256_GCM,data:p4sh2x3N,iv:a5R0+uiwHRnpwLQjUmM13IkaMj4h9+PXz5KNYufbwS8=,tag:sJjDmLicJp7m9VyNVX9GCg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ju0q5ZyVsF5QJXjC6Wb6azvZ0vpo7HQ=,iv:mYs3mqs18oIL46OJfax+E4cY+Ef/15PH8M59du//9Fo=,tag:Phov8CbbkgZcsAtKcIOT+Q==,type:str]
    namespace: ENC[AES256_GCM,data:R1muWiQhsxo=,iv:aoqQTGRG2vYkUfXuw5g+V9t8Frq/WXJuyFBDoen8SHA=,tag:M2PTp2RtR129/vxBokUShA==,type:str]
type: ENC[AES256_GCM,data:ys/V6vyS,iv:E5MLXfSR6Nwea2iov+ZW7XwEUNJbKEa/HJiTxsp5dg0=,tag:kFtJCB/tXPCcuiI+lPJL9Q==,type:str]
stringData:
    #ENC[AES256_GCM,data:Gg2n+IiuxrUYZNBqXz8/whYdgWuF1vv5dBqzz5GvRLfXOTAlxyc+iDTNxnjGPN7/8K+3iIkoEiizzssX,iv:vTq20Qxm1RfE/wFKrPhXK45A61eR5Ri5yn7rQZFFvf8=,tag:VbzxNYCyX3N0hY67zA9H7A==,type:comment]
    #ENC[AES256_GCM,data:nUvJSV/NS7aql0OGd/NeWHyBOVivR3s3w4sH91s3VP7IJan9F9Twh11apZTIofZ00oK/Lh8OwQQ=,iv:6M0IOyv4jkUs4SgLk8WfZk778UvSNB1r+4RPsI9jkIM=,tag:j81/IsvSAgEpMNzArkUEEw==,type:comment]
    #ENC[AES256_GCM,data:XnBLNeNT2TMundYad5JOPpHeUoIV2LOiP0b9GjSnmjQo9Plv89UrqhxaVLyIsPdEtNNZmd5qYabMB3SC0rU+eCYU,iv:HOK1ZDjk+dSAQ0wTLgprceRXW9oR0jpR4Uf6lPfONHI=,tag:nKfPrdMa1Y/o42YXfUSSKw==,type:comment]
    #ENC[AES256_GCM,data:yYA7iyUr63X2mCiAYYLHjq2dTnTbxoczIqL+E/MelKgMkWMxpF4qtUS0kxW+W9wBanTEvsMBYwogdSI9QDDS3CIHNJG8,iv:1ZUvod8RjA4sN/Q7MottAsqdVO62ZEEYGjEBAonaAhc=,tag:hmMdxNNRlEIHkdfxlnYgcA==,type:comment]
    #ENC[AES256_GCM,data:Qj8ke7xeIXBct8QMpoV4V+9b5fUI+APkrp9IJt9mukY+06BuJyISXGnQ5z27NcDWEJqQAdEMCHBrAHSqAew+HM+V+w==,iv:XFQCT6Xj4oeFomul4V0H+RQMy9irFTL+bYn4MWhcWwo=,tag:1EYKJLotN1KB+Z7lqAVpFw==,type:comment]
    #ENC[AES256_GCM,data:vfTl0lpVkJoWd27iQRScn/YM7sLlRABuMt8XYkyYVCLIQ6NBNJh+bz4FF6HjsQKE/EkuzuvKAuXxslQAt996Ceypp5l3XQ==,iv:h/8Ps5vtyxa/B/CAu+0EsQXYkGYnS+YrA4QL5LwdCo4=,tag:1EoR4hdxB09ggQpPm2uC7Q==,type:comment]
    #ENC[AES256_GCM,data:VPvGpySQwIyuxO2z48dFu0UHS7cvOXL3En712/ONJbw+bhpGs2ayrYpftcuVYCMr+GUcGF0yEAYC1VPBZfGRQwhiWQ==,iv:xrzB40OAUFDKMXOfOtvyd83V7ypVnMrf4DiuZVzqJus=,tag:XteLiDrrSV/cDZdu76WvEQ==,type:comment]
    TENANTS: ENC[AES256_GCM,data:X8gn+WSArZ5jY3tzSAS8hqqSRkONuD72/3uZ5ly5ngyRjl0+YicfEqEuSce+3MvH8+6DVlVvJSPR6nVMACAHmgY/E0Iw1AIGQGN4tbqDHWZ79lGHHLV+0VovHYZy1CEaaxQLnTbviJe8E38k5ZyKdOeWamzs2oln6zBYGC9Dv9WHApwDk6qKPbScD/LT0r9nOq10COS5Km1obiloQ4EsHJxwNpSg7MS5ObljiRdaSk7BY1++nDRNIKvxVLS5RNzw2E6lCw9wqZ1Ugj78gAJt8x2HfSC8Fe1NJMbpsl+PqKExutF9EhI7TWLHcFA1orRBDaVuj0qrVWlVKQte8CXXVemt2oS1+ZfEiuuhO4T6IQ==,iv:gu/iGM76NkE+czscp87u+pdDJerD15RfLub38DT3YKs=,tag:rQHIap7ahWgga3s/rwldXw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCMDczU29Da2ZoMmFqN21i
            dTdudWJoVTdia0JFTnlUR3gvM3AyeXVTMnlFCjY0SWpVVGZscmpjMVcyNjYvSFMw
            aDJiK0VQQ0dtN253eXN6ZW52WndoOVkKLS0tIGFQUCs0UDY4Z2ZQWm0rKzZyM1lz
            cm54TGdTSTVGVmtubzJhL05Cc1pxWGcKiyCZIIxOnI3BeSlZSpsVYBENx+4pSNrm
            Wmf2ksxghRHHmFW6Opjkm0N/6g5lT5CAdY1Fzd5G00p9mux28LfU2Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age182ep8d0hyvnwfj3nhzv64xrdvm4fwpudc0wvvkxncqygzzpxkeks4mldng
    lastmodified: "2026-10-06T19:31:29Z"
    mac: ENC[AES256_GCM,data:1jJI0wRcwRwf1iM8WL18x1EkOwIfGI9KRk/NwJWaS210KZoxx1gOxParWgSP7hWmV+4IWGAVv507IYiU4zZ2QGFtYvcWh5HeEPVU8rSkt8YU2quKdc3Jc838QSfp30kFU90SyTFB7KpE+SU4tw719zlWKa4rwqT20hh0j++1nGI=,iv:Cr7oE2RqY3WeFYZWVsJu1xvtPrQDoroMAtKfZOAXmus=,tag:ZXEXzyO+bsB+sIHctXB1IQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
